# Generated by Django 5.1.6 on 2025-02-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(db_index=True, max_length=20, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('vin_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('purchase_document', models.FileField(blank=True, null=True, upload_to='vehicle_documents/purchase/')),
                ('vignette_document', models.FileField(blank=True, null=True, upload_to='vehicle_documents/vignette/')),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='vehicle_documents/registration/')),
                ('fuel_type', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Électrique', 'Électrique'), ('GPL', 'GPL')], max_length=50)),
                ('insurance_company', models.CharField(max_length=100)),
                ('insurance_policy_number', models.CharField(max_length=50)),
                ('insurance_expiry_date', models.DateField()),
                ('last_technical_check', models.DateField()),
                ('next_technical_check', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
                ('documents', models.ManyToManyField(related_name='vehicles', to='vehicles.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='TollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tolltransaction_set', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_tolltransaction_set', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.brand')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclemodel'),
        ),
    ]
